"""商品字段增加进货价

Revision ID: 042d4e18642c
Revises: e8e0a1d4f2b7
Create Date: 2026-06-16 11:05:19.715518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042d4e18642c'
down_revision: Union[str, Sequence[str], None] = 'e8e0a1d4f2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_activity_product', 'activity_product', ['activity_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_activity_product', 'activity_product', type_='unique')
    # ### end Alembic commands ###
