"""增加商品图片绑定商品表

Revision ID: 22554a5a81ff
Revises: d51d5dd96f59
Create Date: 2026-06-11 10:13:01.889290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '22554a5a81ff'
down_revision: Union[str, Sequence[str], None] = 'd51d5dd96f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_image_id'), table_name='product_image')
    op.drop_table('product_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='商品ID'),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=False, comment='图片URL'),
    sa.Column('image_type', mysql.INTEGER(), autoincrement=False, nullable=False, comment='1=轮播图,2=详情图'),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=False, comment='排序'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('product_image_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)
    # ### end Alembic commands ###
