"""购物车模型增加字段

Revision ID: 3dd25001c3b1
Revises: 042d4e18642c
Create Date: 2026-06-16 14:28:46.050769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3dd25001c3b1'
down_revision: Union[str, Sequence[str], None] = '042d4e18642c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cart', sa.Column('price', sa.Float(), nullable=False, comment='商品单价'))
    op.add_column('user_cart', sa.Column('total_price', sa.Float(), nullable=False, comment='商品总金额'))
    op.alter_column('user_cart', 'num',
               existing_type=mysql.INTEGER(),
               comment='数量',
               existing_comment='数量数量',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_cart', 'num',
               existing_type=mysql.INTEGER(),
               comment='数量数量',
               existing_comment='数量',
               existing_nullable=False)
    op.drop_column('user_cart', 'total_price')
    op.drop_column('user_cart', 'price')
    # ### end Alembic commands ###
