"""订单表增加配送类型

Revision ID: 4ba91fab4968
Revises: 3dd25001c3b1
Create Date: 2026-06-18 13:30:10.325398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba91fab4968'
down_revision: Union[str, Sequence[str], None] = '3dd25001c3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_type', sa.Integer(), nullable=True, comment='1 配送 2 自提'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_type')
    # ### end Alembic commands ###
