"""修改SysUser与UserAddress的关联关系

Revision ID: b32892f7d9c6
Revises: bc05a4da5b79
Create Date: 2026-06-03 17:17:43.040618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32892f7d9c6'
down_revision: Union[str, Sequence[str], None] = 'bc05a4da5b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
