"""修改SysUser与UserAddress的关联关系

Revision ID: bc05a4da5b79
Revises: c12329784c04
Create Date: 2026-06-03 17:15:13.244314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc05a4da5b79'
down_revision: Union[str, Sequence[str], None] = 'c12329784c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
