"""修改Product中detail_img的类型

Revision ID: c12329784c04
Revises: 
Create Date: 2026-06-03 17:05:28.565521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c12329784c04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'detail_img',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_comment='详情图片',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'detail_img',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_comment='详情图片',
               existing_nullable=True)
    # ### end Alembic commands ###
