"""修改商品表字段，增加商品图片绑定商品

Revision ID: d51d5dd96f59
Revises: b32892f7d9c6
Create Date: 2026-06-11 09:58:18.558628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd51d5dd96f59'
down_revision: Union[str, Sequence[str], None] = 'b32892f7d9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'detail_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('detail_img', mysql.VARCHAR(length=255), nullable=True, comment='详情图片'))
    # ### end Alembic commands ###
